# Generated by Django 5.1.1 on 2024-10-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('iddispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nomenclatura', models.CharField(max_length=45, unique=True)),
                ('nrodeserie', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'dispositivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialubicacion',
            fields=[
                ('idhistorialubicacion', models.AutoField(db_column='idhistorialUbicacion', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'historialubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UbicEspecifica',
            fields=[
                ('idubic_especifica', models.AutoField(primary_key=True, serialize=False)),
                ('ubic_especifica', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ubic_especifica',
                'managed': False,
            },
        ),
    ]
