# Generated by Django 5.0.4 on 2024-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('iddispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nomenclatura', models.CharField(max_length=45, unique=True)),
                ('nrodeserie', models.CharField(blank=True, max_length=45, null=True)),
                ('jiracompra', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'dispositivo',
                'managed': True,
            },
        ),
    ]
