# Generated by Django 5.1.1 on 2024-10-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('idgerencia', models.AutoField(primary_key=True, serialize=False)),
                ('gerencia', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'gerencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialgerencia',
            fields=[
                ('idhistorialgerencia', models.AutoField(db_column='idhistorialGerencia', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'historialgerencia',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='historialubicacion',
            options={'managed': False, 'verbose_name_plural': 'Historial de Ubicaciones del Dispositivo'},
        ),
    ]
